[package]
name = "svgr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.0", features = ["derive"] }
regex = "1.7.3"
swc = "0.259.2"
swc_common = "0.30.5"
swc_core = { version = "0.74.2", features = ["testing"] }
swc_ecmascript = { version = "0.226.2", features = ["codegen"] }
swc_xml = "0.10.3"
